_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
SOLVER:
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 1000
DATASETS:
  TRAIN: ("train_dora_font",)
  TEST: ("test_dora_font",)
SOLVER:
  IMS_PER_BATCH: 24