_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [103.53, 116.28, 123.675, 0.01]
  PIXEL_STD: [1.0, 1.0, 1.0, 1.0]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 11
  ROI_HEADS:
    NUM_CLASSES: 11
SOLVER:
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 2500
DATASETS:
  TRAIN: ("train_dora_sim",)
  TEST: ("test_dora_sim",)
SOLVER:
  IMS_PER_BATCH: 4
INPUT:
  FORMAT: RGBA