_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 6
  ROI_HEADS:
    NUM_CLASSES: 6
SOLVER:
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 2500
DATASETS:
  TRAIN: ("train_dora_sim",)
  TEST: ("test_dora_sim",)
SOLVER:
  IMS_PER_BATCH: 50